stages:
  load_data:
    cmd: python3 src/get_data.py --config_path paths.yaml --config_params params.yaml
    deps:
    - src/get_data.py
    - data_given/car data.csv
    outs:
    - data/raw/car_data.csv
  preprocessed_data:
    cmd: python3 src/data_prepo.py --config_path paths.yaml
    deps:
    - src/data_prepo.py
    - data/raw/car_data.csv
    outs:
    - data/processed/car_data.csv
  Trainig_data:
    cmd: python3 src/train_test_evaluate.py --config_path paths.yaml --config_params params.yaml
    deps:
    - src/train_test_evaluate.py
    - data/processed/car_data.csv
    params:
    - random_cv.n_iter
    - random_cv.cv
    - random_cv.n_estimators.start
    - random_cv.n_estimators.stop
    - random_cv.n_estimators.num
    # metrics:
    # - report/scores.json:
    #     cache: false
    # - report/params.json:
    #     cache: false
  # log_production_model:
  #   cmd: python src/log_production_model.py --config=params.yaml
  #   deps:
  #   - src/log_production_model.py
    