base:
  split_ratio: 0.2
  random_state: 12

random_cv:
  n_estimators: 
    start : 100
    stop: 1000
    num: 10
  max_features: ['auto', 'sqrt']
  max_depth: 
    start : 5
    stop: 30
    num: 6
  min_samples_split: [2, 5, 10, 15, 100]
  min_samples_leaf: [1, 2, 5, 10]
  n_iter: 5
  cv: 3
webapp_model_dir : prediction_service/model/model.joblib
mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://0.0.0.0:1234

